from decimal import Decimal
# Sample data for listings
sample_listings = [
    {
        'title': 'Modern Downtown Condo',
        'street_address': '123 King Street W',
        'city': 'Toronto',
        'province': 'ON',
        'description': 'Stunning modern condo in the heart of downtown with floor-to-ceiling windows, stainless steel appliances, and building amenities including gym and rooftop terrace.',
        'current_price': Decimal('850000.00'),
        'bedrooms': 2,
        'bathrooms': 2,
        'square_feet': 1200,
        'image_url': 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'
    },
    {
        'title': 'Luxury Waterfront Villa',
        'street_address': '456 Lakeshore Blvd',
        'city': 'Vancouver',
        'province': 'BC',
        'description': 'Spectacular waterfront villa with panoramic ocean views, private beach access, gourmet kitchen, and luxurious master suite with spa-like ensuite.',
        'current_price': Decimal('2500000.00'),
        'bedrooms': 4,
        'bathrooms': 3,
        'square_feet': 3500,
        'image_url': 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800'
    },
    {
        'title': 'Cozy Suburban Home',
        'street_address': '789 Maple Avenue',
        'city': 'Calgary',
        'province': 'AB',
        'description': 'Perfect family home in quiet neighborhood with updated kitchen, finished basement, large backyard, and double garage. Close to schools and parks.',
        'current_price': Decimal('485000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 1800,
        'image_url': 'https://images.unsplash.com/photo-1448630360428-65456885c650?w=800'
    },
    {
        'title': 'Historic Heritage House',
        'street_address': '321 Queen Street',
        'city': 'Montreal',
        'province': 'QC',
        'description': 'Charming heritage home with original hardwood floors, exposed brick walls, modern updates while maintaining historic character. Walking distance to downtown.',
        'current_price': Decimal('675000.00'),
        'bedrooms': 3,
        'bathrooms': 1,
        'square_feet': 2200,
        'image_url': 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800'
    },
    {
        'title': 'Modern Penthouse Suite',
        'street_address': '555 Bay Street',
        'city': 'Toronto',
        'province': 'ON',
        'description': 'Luxurious penthouse with breathtaking city views, private terrace, high-end finishes, and concierge service. Premium location in financial district.',
        'current_price': Decimal('1250000.00'),
        'bedrooms': 2,
        'bathrooms': 2,
        'square_feet': 1600,
        'image_url': 'https://images.unsplash.com/photo-1531971589569-0d9370cbe1e5?w=800'
    },
    {
        'title': 'Family Home with Garden',
        'street_address': '888 Oak Drive',
        'city': 'Ottawa',
        'province': 'ON',
        'description': 'Spacious family home with beautiful landscaped gardens, updated kitchen, master bedroom with walk-in closet, and recreation room. Great for entertaining.',
        'current_price': Decimal('625000.00'),
        'bedrooms': 4,
        'bathrooms': 3,
        'square_feet': 2400,
        'image_url': 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'
    },
    {
        'title': 'Studio Loft Downtown',
        'street_address': '777 Granville Street',
        'city': 'Vancouver',
        'province': 'BC',
        'description': 'Trendy studio loft in vibrant downtown area with exposed concrete, high ceilings, modern appliances, and building amenities. Perfect for young professionals.',
        'current_price': Decimal('425000.00'),
        'bedrooms': 1,
        'bathrooms': 1,
        'square_feet': 650,
        'image_url': 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800'
    },
    {
        'title': 'Spacious Ranch Style',
        'street_address': '999 Prairie Road',
        'city': 'Winnipeg',
        'province': 'MB',
        'description': 'Single-level ranch home with open concept living, vaulted ceilings, fireplace, and large lot. Recent renovations include new flooring and paint throughout.',
        'current_price': Decimal('395000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 2000,
        'image_url': 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800'
    },
    {
        'title': 'Beachfront Cottage',
        'street_address': '111 Coastal Highway',
        'city': 'Halifax',
        'province': 'NS',
        'description': 'Charming beachfront cottage with stunning ocean views, stone fireplace, wraparound deck, and private beach access. Perfect weekend retreat or year-round home.',
        'current_price': Decimal('550000.00'),
        'bedrooms': 2,
        'bathrooms': 1,
        'square_feet': 1100,
        'image_url': 'https://plus.unsplash.com/premium_photo-1689609950112-d66095626efb?w=800'
    },
    {
        'title': 'Executive Townhouse',
        'street_address': '222 Executive Drive',
        'city': 'Edmonton',
        'province': 'AB',
        'description': 'Elegant three-story townhouse with premium finishes, gourmet kitchen with granite counters, master suite with luxury ensuite, and attached garage.',
        'current_price': Decimal('725000.00'),
        'bedrooms': 3,
        'bathrooms': 3,
        'square_feet': 2100,
        'image_url': 'https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=800'
    },
    {
        'title': 'High-Rise Luxury Condo',
        'street_address': '1001 Robson Street',
        'city': 'Vancouver',
        'province': 'BC',
        'description': 'Premium high-rise condo with mountain and city views, floor-to-ceiling windows, marble countertops, and world-class amenities including pool, spa, and fitness center.',
        'current_price': Decimal('1350000.00'),
        'bedrooms': 2,
        'bathrooms': 2,
        'square_feet': 1400,
        'image_url': 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800'
    },
    {
        'title': 'Vintage Character Home',
        'street_address': '456 Heritage Avenue',
        'city': 'Victoria',
        'province': 'BC',
        'description': 'Restored 1920s character home with original crown molding, stained glass windows, updated electrical and plumbing, and mature garden with fruit trees.',
        'current_price': Decimal('875000.00'),
        'bedrooms': 4,
        'bathrooms': 2,
        'square_feet': 2600,
        'image_url': 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800'
    },
    {
        'title': 'Modern Duplex Investment',
        'street_address': '789 Investment Lane',
        'city': 'Calgary',
        'province': 'AB',
        'description': 'Brand new duplex with separate entrances, contemporary design, energy-efficient features, and excellent rental potential in growing neighborhood.',
        'current_price': Decimal('650000.00'),
        'bedrooms': 6,
        'bathrooms': 4,
        'square_feet': 2800,
        'image_url': 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'
    },
    {
        'title': 'Lakefront Log Cabin',
        'street_address': '123 Pine Lake Road',
        'city': 'Muskoka',
        'province': 'ON',
        'description': 'Rustic log cabin on pristine lake with private dock, stone fireplace, vaulted ceilings, and 200 feet of waterfront. Perfect for outdoor enthusiasts.',
        'current_price': Decimal('950000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 1900,
        'image_url': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800'
    },
    {
        'title': 'Downtown Loft Conversion',
        'street_address': '345 Industrial Street',
        'city': 'Montreal',
        'province': 'QC',
        'description': 'Converted warehouse loft with 14-foot ceilings, exposed brick and beams, polished concrete floors, and oversized windows. Trendy Plateau location.',
        'current_price': Decimal('525000.00'),
        'bedrooms': 1,
        'bathrooms': 1,
        'square_feet': 1100,
        'image_url': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'
    },
    {
        'title': 'Suburban McMansion',
        'street_address': '888 Country Club Drive',
        'city': 'Mississauga',
        'province': 'ON',
        'description': 'Impressive two-story home in prestigious neighborhood with grand foyer, chef kitchen, home theater, wine cellar, and professionally landscaped grounds.',
        'current_price': Decimal('1650000.00'),
        'bedrooms': 5,
        'bathrooms': 4,
        'square_feet': 4200,
        'image_url': 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'
    },
    {
        'title': 'Affordable Starter Home',
        'street_address': '567 First Time Street',
        'city': 'Saskatoon',
        'province': 'SK',
        'description': 'Perfect starter home with recent updates including new roof, windows, and flooring. Fenced yard, single garage, and close to schools and shopping.',
        'current_price': Decimal('285000.00'),
        'bedrooms': 3,
        'bathrooms': 1,
        'square_feet': 1200,
        'image_url': 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800'
    },
    {
        'title': 'Coastal Modern Retreat',
        'street_address': '999 Ocean View Drive',
        'city': 'Tofino',
        'province': 'BC',
        'description': 'Contemporary West Coast retreat with floor-to-ceiling glass, natural cedar siding, radiant heating, and spectacular ocean and forest views.',
        'current_price': Decimal('1850000.00'),
        'bedrooms': 3,
        'bathrooms': 3,
        'square_feet': 2400,
        'image_url': 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800'
    },
    {
        'title': 'Historic Brownstone',
        'street_address': '234 Heritage Row',
        'city': 'Quebec City',
        'province': 'QC',
        'description': 'Magnificent 19th-century brownstone in Old Quebec with original stone walls, modern amenities, rooftop terrace, and walking distance to historic sites.',
        'current_price': Decimal('775000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 2000,
        'image_url': 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800'
    },
    {
        'title': 'Energy-Efficient New Build',
        'street_address': '777 Green Technology Way',
        'city': 'Kitchener',
        'province': 'ON',
        'description': 'LEED-certified new construction with solar panels, geothermal heating, smart home technology, and premium energy-efficient appliances throughout.',
        'current_price': Decimal('685000.00'),
        'bedrooms': 4,
        'bathrooms': 3,
        'square_feet': 2300,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Mountain View Chalet',
        'street_address': '100 Alpine Ridge Road',
        'city': 'Banff',
        'province': 'AB',
        'description': 'Stunning alpine chalet with panoramic mountain views, stone fireplace, cedar beam construction, and hot tub on private deck. Perfect ski retreat.',
        'current_price': Decimal('1250000.00'),
        'bedrooms': 4,
        'bathrooms': 3,
        'square_feet': 2800,
        'image_url': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800'
    },
    {
        'title': 'Luxury Penthouse Loft',
        'street_address': '500 Richmond Street W',
        'city': 'Toronto',
        'province': 'ON',
        'description': 'Ultra-modern penthouse with 20-foot ceilings, wraparound terrace, chef kitchen, wine room, and stunning CN Tower views. Building amenities include concierge.',
        'current_price': Decimal('2850000.00'),
        'bedrooms': 3,
        'bathrooms': 3,
        'square_feet': 2200,
        'image_url': 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'
    },
    {
        'title': 'Craftsman Bungalow',
        'street_address': '888 Elm Street',
        'city': 'Regina',
        'province': 'SK',
        'description': 'Charming 1930s craftsman bungalow with original hardwood, built-in cabinets, leaded glass windows, and completely renovated kitchen and bathrooms.',
        'current_price': Decimal('365000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 1600,
        'image_url': 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800'
    },
    {
        'title': 'Waterfront Condo Tower',
        'street_address': '1200 Marine Drive',
        'city': 'Vancouver',
        'province': 'BC',
        'description': 'Luxury waterfront condo with floor-to-ceiling windows, marble finishes, European appliances, and panoramic ocean and mountain views. Resort-style amenities.',
        'current_price': Decimal('1750000.00'),
        'bedrooms': 2,
        'bathrooms': 2,
        'square_feet': 1300,
        'image_url': 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'
    },
    {
        'title': 'Country Estate Farmhouse',
        'street_address': '1500 Country Lane',
        'city': 'Charlottetown',
        'province': 'PE',
        'description': 'Historic farmhouse on 50 acres with restored original features, modern amenities, barn, and panoramic countryside views. Perfect for equestrian enthusiasts.',
        'current_price': Decimal('825000.00'),
        'bedrooms': 5,
        'bathrooms': 3,
        'square_feet': 3200,
        'image_url': 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'
    },
    {
        'title': 'Modern Micro Condo',
        'street_address': '350 King Street E',
        'city': 'Toronto',
        'province': 'ON',
        'description': 'Efficiently designed micro condo with innovative storage solutions, murphy bed, premium finishes, and building amenities. Perfect for downtown living.',
        'current_price': Decimal('425000.00'),
        'bedrooms': 1,
        'bathrooms': 1,
        'square_feet': 450,
        'image_url': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'
    },
    {
        'title': 'Acreage with Custom Home',
        'street_address': '2000 Rural Route 3',
        'city': 'Red Deer',
        'province': 'AB',
        'description': 'Custom-built home on 10 acres with chef kitchen, wine cellar, home theater, workshop, and stunning prairie views. Complete privacy and luxury.',
        'current_price': Decimal('1450000.00'),
        'bedrooms': 4,
        'bathrooms': 4,
        'square_feet': 3800,
        'image_url': 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'
    },
    {
        'title': 'Historic Mansion',
        'street_address': '1867 Grande Allée',
        'city': 'Quebec City',
        'province': 'QC',
        'description': 'Magnificent 1800s mansion with period details, grand staircase, library, conservatory, and formal gardens. Completely restored with modern systems.',
        'current_price': Decimal('3200000.00'),
        'bedrooms': 6,
        'bathrooms': 5,
        'square_feet': 5500,
        'image_url': 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800'
    },
    {
        'title': 'Ski Chalet Townhouse',
        'street_address': '75 Whistler Village',
        'city': 'Whistler',
        'province': 'BC',
        'description': 'Luxury ski-in/ski-out townhouse with stone fireplace, heated floors, hot tub, and mountain views. Short-term rental approved for investment income.',
        'current_price': Decimal('1950000.00'),
        'bedrooms': 3,
        'bathrooms': 3,
        'square_feet': 2100,
        'image_url': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800'
    },
    {
        'title': 'Affordable Duplex',
        'street_address': '444 Working Class Avenue',
        'city': 'Thunder Bay',
        'province': 'ON',
        'description': 'Well-maintained duplex with separate entrances, updated kitchens, hardwood floors, and strong rental history. Great investment opportunity.',
        'current_price': Decimal('295000.00'),
        'bedrooms': 4,
        'bathrooms': 2,
        'square_feet': 1800,
        'image_url': 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'
    },
    {
        'title': 'Solar-Powered Modern Home',
        'street_address': '123 Sustainable Street',
        'city': 'Kelowna',
        'province': 'BC',
        'description': 'Net-zero energy home with solar panels, geothermal heating, rainwater collection, and premium sustainable materials throughout. Lake views included.',
        'current_price': Decimal('895000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 2000,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Victorian Conversion',
        'street_address': '200 Heritage Hill',
        'city': 'St. Johns',
        'province': 'NL',
        'description': 'Beautifully converted Victorian home with period details, bay windows, decorative moldings, and harbor views. Walking distance to downtown.',
        'current_price': Decimal('485000.00'),
        'bedrooms': 4,
        'bathrooms': 2,
        'square_feet': 2400,
        'image_url': 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800'
    },
    {
        'title': 'Executive Bungalow',
        'street_address': '999 Executive Circle',
        'city': 'London',
        'province': 'ON',
        'description': 'Luxury single-story home with open concept, cathedral ceilings, gourmet kitchen, master suite with spa ensuite, and professionally landscaped yard.',
        'current_price': Decimal('785000.00'),
        'bedrooms': 3,
        'bathrooms': 3,
        'square_feet': 2600,
        'image_url': 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'
    },
    {
        'title': 'Urban Townhouse',
        'street_address': '567 City Center Way',
        'city': 'Hamilton',
        'province': 'ON',
        'description': 'Modern three-story townhouse with rooftop deck, integrated garage, smart home features, and walking distance to GO station. Perfect for commuters.',
        'current_price': Decimal('675000.00'),
        'bedrooms': 3,
        'bathrooms': 3,
        'square_feet': 1900,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Cottage Country Retreat',
        'street_address': '888 Cottage Road',
        'city': 'Huntsville',
        'province': 'ON',
        'description': 'Four-season cottage on private lake with sandy beach, dock, stone fireplace, and screened porch. Turn-key and fully furnished.',
        'current_price': Decimal('750000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 1700,
        'image_url': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800'
    },
    {
        'title': 'Student Housing Investment',
        'street_address': '123 University Avenue',
        'city': 'Kingston',
        'province': 'ON',
        'description': 'Six-bedroom student rental property near Queens University with separate leases, updated systems, and strong rental income history.',
        'current_price': Decimal('525000.00'),
        'bedrooms': 6,
        'bathrooms': 3,
        'square_feet': 2200,
        'image_url': 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'
    },
    {
        'title': 'Luxury Golf Course Home',
        'street_address': '18 Fairway Drive',
        'city': 'Niagara-on-the-Lake',
        'province': 'ON',
        'description': 'Stunning home overlooking 18th hole with wine cellar, gourmet kitchen, library, and resort-style master suite. Golf membership included.',
        'current_price': Decimal('1650000.00'),
        'bedrooms': 4,
        'bathrooms': 4,
        'square_feet': 3600,
        'image_url': 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'
    },
    {
        'title': 'Converted Church Loft',
        'street_address': '456 Sacred Heart Street',
        'city': 'Montreal',
        'province': 'QC',
        'description': 'Unique converted church loft with 25-foot ceilings, stained glass windows, exposed beams, and original architectural details. One-of-a-kind living.',
        'current_price': Decimal('985000.00'),
        'bedrooms': 2,
        'bathrooms': 2,
        'square_feet': 2400,
        'image_url': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'
    },
    {
        'title': 'Retirement Bungalow',
        'street_address': '777 Golden Years Lane',
        'city': 'Vernon',
        'province': 'BC',
        'description': 'Single-level home perfect for retirement with no-step entry, wide hallways, accessible bathrooms, and low-maintenance yard. Lake and mountain views.',
        'current_price': Decimal('595000.00'),
        'bedrooms': 2,
        'bathrooms': 2,
        'square_feet': 1400,
        'image_url': 'https://images.unsplash.com/photo-1566908829077-38227b70c31b?w=800'
    },
    {
        'title': 'Riverfront Log Home',
        'street_address': '250 Wilderness Trail',
        'city': 'Canmore',
        'province': 'AB',
        'description': 'Handcrafted log home on Bow River with private fishing access, timber frame construction, stone fireplace, and breathtaking mountain views.',
        'current_price': Decimal('1350000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 2200,
        'image_url': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800'
    },
    {
        'title': 'Industrial Loft Warehouse',
        'street_address': '88 Factory Street',
        'city': 'Toronto',
        'province': 'ON',
        'description': 'Converted warehouse loft with soaring 18-foot ceilings, exposed brick, steel beams, and massive windows. Raw industrial charm meets modern luxury.',
        'current_price': Decimal('1125000.00'),
        'bedrooms': 2,
        'bathrooms': 2,
        'square_feet': 1800,
        'image_url': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'
    },
    {
        'title': 'Farmhouse with Vineyard',
        'street_address': '1200 Wine Country Road',
        'city': 'Oliver',
        'province': 'BC',
        'description': 'Working vineyard estate with restored farmhouse, wine cellar, tasting room, and 25 acres of premium grape varietals. Established wine business.',
        'current_price': Decimal('2750000.00'),
        'bedrooms': 4,
        'bathrooms': 3,
        'square_feet': 3000,
        'image_url': 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'
    },
    {
        'title': 'Downtown Artist Studio',
        'street_address': '42 Creative Quarter',
        'city': 'Montreal',
        'province': 'QC',
        'description': 'Light-filled artist studio with 12-foot ceilings, north-facing windows, polished concrete floors, and live/work zoning in vibrant arts district.',
        'current_price': Decimal('465000.00'),
        'bedrooms': 1,
        'bathrooms': 1,
        'square_feet': 900,
        'image_url': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'
    },
    {
        'title': 'Historic Lighthouse Keeper Home',
        'street_address': '1 Beacon Point',
        'city': 'Peggy\'s Cove',
        'province': 'NS',
        'description': 'Unique lighthouse keeper residence with panoramic ocean views, restored original features, and exclusive access to historic lighthouse grounds.',
        'current_price': Decimal('875000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 1600,
        'image_url': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800'
    },
    {
        'title': 'Contemporary Glass House',
        'street_address': '500 Modernist Way',
        'city': 'West Vancouver',
        'province': 'BC',
        'description': 'Stunning glass and steel contemporary home with panoramic ocean views, infinity pool, wine cellar, and smart home automation throughout.',
        'current_price': Decimal('4250000.00'),
        'bedrooms': 4,
        'bathrooms': 5,
        'square_feet': 4500,
        'image_url': 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800'
    },
    {
        'title': 'Prairie Heritage Schoolhouse',
        'street_address': '150 Heritage School Road',
        'city': 'Dauphin',
        'province': 'MB',
        'description': 'Converted 1910 schoolhouse with original chalkboards, high ceilings, hardwood floors, and modern kitchen addition. Unique character home.',
        'current_price': Decimal('325000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 2000,
        'image_url': 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800'
    },
    {
        'title': 'Floating Home Marina',
        'street_address': '25 Floating Dock',
        'city': 'Victoria',
        'province': 'BC',
        'description': 'Unique floating home with marina berth, 360-degree water views, modern amenities, and exclusive marina community with floating gardens.',
        'current_price': Decimal('725000.00'),
        'bedrooms': 2,
        'bathrooms': 1,
        'square_feet': 1200,
        'image_url': 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800'
    },
    {
        'title': 'Eco-Dome Earth Home',
        'street_address': '333 Sustainable Circle',
        'city': 'Nelson',
        'province': 'BC',
        'description': 'Innovative earth-sheltered dome home with passive solar design, rainwater harvesting, permaculture gardens, and off-grid capabilities.',
        'current_price': Decimal('495000.00'),
        'bedrooms': 2,
        'bathrooms': 1,
        'square_feet': 1100,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Penthouse Sky Bridge',
        'street_address': '2000 Sky Tower',
        'city': 'Calgary',
        'province': 'AB',
        'description': 'Ultra-luxury penthouse connected by private sky bridge with helicopter pad, wine cellar, home theater, and unobstructed mountain views.',
        'current_price': Decimal('5500000.00'),
        'bedrooms': 5,
        'bathrooms': 6,
        'square_feet': 6000,
        'image_url': 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'
    },
    {
        'title': 'Converted Fire Station',
        'street_address': '911 Emergency Avenue',
        'city': 'Ottawa',
        'province': 'ON',
        'description': 'Unique converted fire station with original brass pole, apparatus bay converted to great room, and heritage designation with modern updates.',
        'current_price': Decimal('985000.00'),
        'bedrooms': 3,
        'bathrooms': 3,
        'square_feet': 2800,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Tiny House Village',
        'street_address': '42 Minimalist Lane',
        'city': 'Squamish',
        'province': 'BC',
        'description': 'Custom tiny house on wheels in eco-village community with shared gardens, workshop space, and mountain adventure access. Sustainable living.',
        'current_price': Decimal('185000.00'),
        'bedrooms': 1,
        'bathrooms': 1,
        'square_feet': 400,
        'image_url': 'https://images.unsplash.com/photo-1566908829077-38227b70c31b?w=800'
    },
    {
        'title': 'Castle-Style Manor',
        'street_address': '1 Royal Court',
        'city': 'Stratford',
        'province': 'ON',
        'description': 'Spectacular castle-inspired manor with turrets, grand ballroom, library, wine cellar, and 20 acres of manicured gardens and woodlands.',
        'current_price': Decimal('3950000.00'),
        'bedrooms': 7,
        'bathrooms': 6,
        'square_feet': 8500,
        'image_url': 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800'
    },
    {
        'title': 'Shipping Container Home',
        'street_address': '888 Industrial Park',
        'city': 'Saskatoon',
        'province': 'SK',
        'description': 'Innovative shipping container conversion with rooftop deck, solar panels, modern interior design, and minimal environmental footprint.',
        'current_price': Decimal('315000.00'),
        'bedrooms': 2,
        'bathrooms': 1,
        'square_feet': 960,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Island Private Estate',
        'street_address': '1 Private Island',
        'city': 'Thousand Islands',
        'province': 'ON',
        'description': 'Exclusive private island estate with helicopter pad, deep-water dock, guest cottages, and complete privacy on 15-acre forested island.',
        'current_price': Decimal('7500000.00'),
        'bedrooms': 6,
        'bathrooms': 7,
        'square_feet': 7500,
        'image_url': 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800'
    },
    {
        'title': 'Geodesic Dome Home',
        'street_address': '360 Geometry Drive',
        'city': 'Yellowknife',
        'province': 'NT',
        'description': 'Unique geodesic dome home designed for extreme weather with aurora viewing dome, radiant heating, and spectacular wilderness views.',
        'current_price': Decimal('485000.00'),
        'bedrooms': 2,
        'bathrooms': 2,
        'square_feet': 1400,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Converted Grain Elevator',
        'street_address': '100 Prairie Heritage',
        'city': 'Moose Jaw',
        'province': 'SK',
        'description': 'Historic grain elevator converted to unique vertical home with observation deck, original machinery features, and panoramic prairie views.',
        'current_price': Decimal('425000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 1800,
        'image_url': 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800'
    },
    {
        'title': 'Underground Earth Home',
        'street_address': '777 Subterranean Way',
        'city': 'Whitehorse',
        'province': 'YT',
        'description': 'Energy-efficient underground home with skylights, geothermal heating, and natural insulation. Unique arctic architecture with modern amenities.',
        'current_price': Decimal('395000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 1600,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Treehouse Retreat',
        'street_address': '50 Canopy Heights',
        'city': 'Algonquin Park',
        'province': 'ON',
        'description': 'Luxury treehouse with suspension bridges, forest canopy views, eco-friendly features, and private hiking trails. Ultimate nature retreat.',
        'current_price': Decimal('650000.00'),
        'bedrooms': 2,
        'bathrooms': 1,
        'square_feet': 800,
        'image_url': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800'
    },
    {
        'title': 'Luxury Penthouse with Terrace',
        'street_address': '1888 Yonge Street',
        'city': 'Toronto',
        'province': 'ON',
        'description': 'Stunning penthouse with wraparound terrace, panoramic city views, floor-to-ceiling windows, and premium finishes. Building amenities include pool and concierge.',
        'current_price': Decimal('2150000.00'),
        'bedrooms': 3,
        'bathrooms': 3,
        'square_feet': 2100,
        'image_url': 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'
    },
    {
        'title': 'Beachfront Modern Home',
        'street_address': '275 Beach Avenue',
        'city': 'White Rock',
        'province': 'BC',
        'description': 'Contemporary beachfront home with wall-to-wall windows, open concept design, gourmet kitchen, and direct beach access. Perfect for entertaining.',
        'current_price': Decimal('1850000.00'),
        'bedrooms': 4,
        'bathrooms': 3,
        'square_feet': 2800,
        'image_url': 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800'
    },
    {
        'title': 'Family Home with Pool',
        'street_address': '456 Riverside Drive',
        'city': 'Windsor',
        'province': 'ON',
        'description': 'Spacious family home with in-ground pool, finished basement, updated kitchen, and large deck overlooking the Detroit River. Great for families.',
        'current_price': Decimal('525000.00'),
        'bedrooms': 4,
        'bathrooms': 3,
        'square_feet': 2300,
        'image_url': 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'
    },
    {
        'title': 'Downtown Live-Work Studio',
        'street_address': '88 Queen Street E',
        'city': 'Toronto',
        'province': 'ON',
        'description': 'Versatile live-work studio with high ceilings, exposed brick, large windows, and separate entrance. Perfect for artists or entrepreneurs.',
        'current_price': Decimal('495000.00'),
        'bedrooms': 1,
        'bathrooms': 1,
        'square_feet': 850,
        'image_url': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'
    },
    {
        'title': 'Luxury Mountain Chalet',
        'street_address': '150 Panorama Ridge',
        'city': 'Whistler',
        'province': 'BC',
        'description': 'Spectacular mountain chalet with vaulted ceilings, stone fireplace, hot tub, and ski-in/ski-out access. High-end finishes throughout.',
        'current_price': Decimal('2350000.00'),
        'bedrooms': 5,
        'bathrooms': 4,
        'square_feet': 3200,
        'image_url': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800'
    },
    {
        'title': 'Heritage Brick Townhouse',
        'street_address': '234 St. George Street',
        'city': 'Toronto',
        'province': 'ON',
        'description': 'Beautiful heritage townhouse with original details, modern kitchen, finished basement, and private garden. Steps from University of Toronto.',
        'current_price': Decimal('1285000.00'),
        'bedrooms': 3,
        'bathrooms': 3,
        'square_feet': 2000,
        'image_url': 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800'
    },
    {
        'title': 'Modern Suburban New Build',
        'street_address': '789 Innovation Way',
        'city': 'Oakville',
        'province': 'ON',
        'description': 'Brand new modern home with smart home technology, quartz countertops, hardwood floors, and energy-efficient features. Move-in ready.',
        'current_price': Decimal('1450000.00'),
        'bedrooms': 4,
        'bathrooms': 4,
        'square_feet': 3000,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Affordable Starter Condo',
        'street_address': '123 First Home Avenue',
        'city': 'Mississauga',
        'province': 'ON',
        'description': 'Perfect starter condo with updated kitchen, in-suite laundry, balcony, and building amenities. Close to transit and shopping.',
        'current_price': Decimal('385000.00'),
        'bedrooms': 1,
        'bathrooms': 1,
        'square_feet': 600,
        'image_url': 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'
    },
    {
        'title': 'Lakefront Cottage',
        'street_address': '456 Lake View Road',
        'city': 'Gravenhurst',
        'province': 'ON',
        'description': 'Charming lakefront cottage with private dock, stone fireplace, screened porch, and stunning sunset views. Perfect weekend getaway.',
        'current_price': Decimal('775000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 1400,
        'image_url': 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800'
    },
    {
        'title': 'Executive Detached Home',
        'street_address': '888 Executive Boulevard',
        'city': 'Markham',
        'province': 'ON',
        'description': 'Impressive executive home with grand foyer, gourmet kitchen, home office, wine cellar, and professionally landscaped gardens.',
        'current_price': Decimal('1825000.00'),
        'bedrooms': 5,
        'bathrooms': 5,
        'square_feet': 4200,
        'image_url': 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'
    },
    {
        'title': 'Urban Loft with Skylight',
        'street_address': '999 King Street W',
        'city': 'Toronto',
        'province': 'ON',
        'description': 'Bright urban loft with skylights, exposed brick, polished concrete floors, and rooftop access. Trendy Queen West location.',
        'current_price': Decimal('725000.00'),
        'bedrooms': 1,
        'bathrooms': 1,
        'square_feet': 950,
        'image_url': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'
    },
    {
        'title': 'Waterfront Luxury Condo',
        'street_address': '1500 Harbourfront Drive',
        'city': 'Vancouver',
        'province': 'BC',
        'description': 'Premium waterfront condo with floor-to-ceiling windows, marble finishes, and panoramic harbor views. World-class amenities and concierge.',
        'current_price': Decimal('1650000.00'),
        'bedrooms': 2,
        'bathrooms': 2,
        'square_feet': 1250,
        'image_url': 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'
    },
    {
        'title': 'Countryside Estate Home',
        'street_address': '2500 Country Estate Lane',
        'city': 'King City',
        'province': 'ON',
        'description': 'Magnificent estate home on 5 acres with circular driveway, indoor pool, tennis court, and horse stables. Ultimate luxury living.',
        'current_price': Decimal('4250000.00'),
        'bedrooms': 6,
        'bathrooms': 7,
        'square_feet': 6500,
        'image_url': 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800'
    },
    {
        'title': 'Cozy Bungalow',
        'street_address': '333 Peaceful Street',
        'city': 'Burlington',
        'province': 'ON',
        'description': 'Charming single-story bungalow with updated kitchen, hardwood floors, finished basement, and mature trees. Perfect for downsizing.',
        'current_price': Decimal('675000.00'),
        'bedrooms': 3,
        'bathrooms': 2,
        'square_feet': 1600,
        'image_url': 'https://images.unsplash.com/photo-1566908829077-38227b70c31b?w=800'
    },
    {
        'title': 'Investment Duplex Property',
        'street_address': '444 Rental Avenue',
        'city': 'Oshawa',
        'province': 'ON',
        'description': 'Well-maintained duplex with separate entrances, updated units, strong rental history, and excellent cash flow potential.',
        'current_price': Decimal('595000.00'),
        'bedrooms': 4,
        'bathrooms': 4,
        'square_feet': 2400,
        'image_url': 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'
    },
    {
        'title': 'Modern Townhouse Complex',
        'street_address': '555 Modern Living Way',
        'city': 'Richmond Hill',
        'province': 'ON',
        'description': 'Contemporary townhouse with open concept, granite counters, stainless appliances, and attached garage. Family-friendly community.',
        'current_price': Decimal('925000.00'),
        'bedrooms': 3,
        'bathrooms': 3,
        'square_feet': 1850,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Eco-Friendly Smart Home',
        'street_address': '777 Green Technology Drive',
        'city': 'Aurora',
        'province': 'ON',
        'description': 'LEED-certified home with solar panels, smart home automation, energy-efficient appliances, and sustainable building materials throughout.',
        'current_price': Decimal('825000.00'),
        'bedrooms': 4,
        'bathrooms': 3,
        'square_feet': 2200,
        'image_url': 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'
    },
    {
        'title': 'Luxury High-Rise Condo',
        'street_address': '1200 Bloor Street W',
        'city': 'Toronto',
        'province': 'ON',
        'description': 'Premium high-rise condo with city views, marble bathrooms, gourmet kitchen, and resort-style amenities including rooftop pool and gym.',
        'current_price': Decimal('1125000.00'),
        'bedrooms': 2,
        'bathrooms': 2,
        'square_feet': 1100,
        'image_url': 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'
    },
    {
        'title': 'Historic Renovated Farmhouse',
        'street_address': '150 Heritage Farm Road',
        'city': 'Georgetown',
        'province': 'ON',
        'description': 'Beautifully renovated 1890s farmhouse with original beams, modern kitchen, wrap-around porch, and 2-acre lot with mature trees.',
        'current_price': Decimal('1350000.00'),
        'bedrooms': 4,
        'bathrooms': 3,
        'square_feet': 2800,
        'image_url': 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800'
    }
]