version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build: ./frontend/lynapp-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/lynapp-react:/app
      - /app/node_modules
    depends_on:
      - backend