# Generated by Django 5.2.1 on 2025-05-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
