# Generated by Django 5.2.1 on 2025-05-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_pricehistory_date_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='date_recorded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
