# Generated by Django 4.2.21 on 2025-07-23 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_pricehistory_date_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.TextField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_caches', to='listings.listing')),
                ('price_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_caches', to='listings.pricehistory')),
            ],
        ),
    ]
